name: smart_closet
description: Weather and context based outfit recommendation app.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  geolocator: ^13.0.2
  http: ^1.2.1
  image_picker: ^1.1.2
  path: ^1.9.0
  shared_preferences: ^2.3.2
  supabase_flutter: ^2.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
